# Generated by Django 5.1.7 on 2025-04-07 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_company_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tech_lead',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'tech_lead'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_companies', to=settings.AUTH_USER_MODEL),
        ),
    ]
