# Generated by Django 5.1.7 on 2025-05-01 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_checklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='company',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='users.company'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_titles', to='users.company')),
            ],
        ),
        migrations.AlterField(
            model_name='checklist',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='users.jobtitle'),
        ),
    ]
