# Generated by Django 5.1.7 on 2025-05-01 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_checklist_company_jobtitle_alter_checklist_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='company',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='users.company'),
        ),
    ]
