# Generated by Django 5.1.7 on 2025-05-01 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_checklist_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checklist',
        ),
    ]
