# Generated by Django 5.1.7 on 2025-05-01 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_checklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='company',
        ),
    ]
