# Generated by Django 5.1.7 on 2025-05-01 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_checklist_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='company',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='users.company'),
            preserve_default=False,
        ),
    ]
