# Generated by Django 5.1.7 on 2025-05-02 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_checklist_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetencyMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.checklist')),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_matrices', to='users.jobtitle')),
            ],
        ),
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='users.competencymatrix')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.competencymatrix')),
            ],
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='users.process')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.competency')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.criterion')),
            ],
        ),
    ]
