# Generated by Django 5.1.7 on 2025-05-02 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_incident'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='users.competencymatrix')),
            ],
        ),
        migrations.AddField(
            model_name='process',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='users.processgroup'),
            preserve_default=False,
        ),
    ]
