# Generated by Django 5.1.7 on 2025-05-02 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_processgroup_process_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.competency')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.incident')),
            ],
        ),
    ]
