# Generated by Django 5.1.7 on 2025-05-04 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_checkmethod_criteriaassessment_zassessment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='group',
        ),
        migrations.AddField(
            model_name='checkmethod',
            name='company',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AddField(
            model_name='criteriaassessment',
            name='company',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='users.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zassessment',
            name='company',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='users.company'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProcessSubGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='users.processgroup')),
            ],
        ),
        migrations.AddField(
            model_name='process',
            name='subgroup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='users.processsubgroup'),
            preserve_default=False,
        ),
    ]
