# Generated by Django 5.1.7 on 2025-05-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_checklistfilling_criterionassessmententry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistfilling',
            name='json_data',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
