# Generated by Django 5.1.7 on 2025-05-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_checklistfilling_json_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='title',
            field=models.CharField(default='checklist #1', max_length=255),
            preserve_default=False,
        ),
    ]
