# Generated by Django 5.1.7 on 2025-05-19 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_checklist_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetencyChecklistFilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competency_json', models.JSONField()),
                ('filling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.checklistfilling')),
            ],
        ),
    ]
