# Generated by Django 5.1.7 on 2025-05-19 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_competencychecklistfilling'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencychecklistfilling',
            name='checklist',
            field=models.ForeignKey(default=27, on_delete=django.db.models.deletion.CASCADE, to='users.checklist'),
            preserve_default=False,
        ),
    ]
