# Generated by Django 5.1.7 on 2025-05-20 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_competencychecklistfilling_checklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultsChecklistFilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencies_json', models.JSONField()),
                ('competencies_summary_json', models.JSONField()),
                ('processes_data', models.JSONField()),
                ('processes_summary', models.JSONField()),
                ('filling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.checklistfilling')),
            ],
        ),
    ]
